# Copyright 2024 Louis Royer. All rights reserved.
# Use of this source code is governed by a MIT-style license that can be
# found in the LICENSE file.
# SPDX-License-Identifier: MIT
config:
  topology:
    nb_edges: 2
    nb_ue: 1
    dataplane: # ( nextmn-srv6 | free5gc | nextmn-upf)
    - "nextmn-srv6"
    log_level: "info"
    full_debug: false

subnets:
  ran:
    gnb1:
      ipv4_address: 10.1.0.129
      ipv6_address: fd00:0:0:0:1:8000:0:2
    gnb2:
      ipv4_address: 10.1.0.130
      ipv6_address: fd00:0:0:0:1:8000:0:3
  sbi:
    amf:
      ipv4_address: 10.1.1.129
    smf:
      ipv4_address: 10.1.1.130
    nrf:
      ipv4_address: 10.1.1.131
    ausf:
      ipv4_address: 10.1.1.132
    nssf:
      ipv4_address: 10.1.1.133
    pcf:
      ipv4_address: 10.1.1.134
    udm:
      ipv4_address: 10.1.1.135
    udr:
      ipv4_address: 10.1.1.136
    chf:
      ipv4_address: 10.1.1.137
    webconsole:
      ipv4_address: 10.1.1.138
  control:
    gnb1:
      ipv4_address: 10.1.3.129
    gnb2:
      ipv4_address: 10.1.3.130
    srgw0:
      ipv4_address: 10.1.3.131
      ipv6_address: fd00:0:0:0:2:8000:0:2
    srv6-ctrl:
      ipv4_address: 10.1.3.132
      ipv6_address: fd00:0:0:0:2:8000:0:6
    rr:
      ipv6_address: fd00:0:0:0:2:8000:0:3
    r0:
      ipv6_address: fd00:0:0:0:2:8000:0:4
    r1:
      ipv6_address: fd00:0:0:0:2:8000:0:5
    amf:
      ipv4_address: 10.1.3.133
    smf:
      ipv4_address: 10.1.3.134
    upfi:
      ipv4_address: 10.1.3.135
    upfa1:
      ipv4_address: 10.1.3.136
    upfa2:
      ipv4_address: 10.1.3.137
  dataplane:
    gnb1:
      ipv4_address: 10.1.4.129
    gnb2:
      ipv4_address: 10.1.4.130
    srgw0:
      ipv4_address: 10.1.4.131
      ipv6_address: fd00:0:0:0:3:8000:0:2
    r0:
      ipv6_address: fd00:0:0:0:3:8000:0:3
    r1:
      ipv6_address: fd00:0:0:0:3:8000:0:4
    rr:
      ipv6_address: fd00:0:0:0:3:8000:0:5
    upfi:
      ipv4_address: 10.1.4.132
    upfa1:
      ipv4_address: 10.1.4.133
    upfa2:
      ipv4_address: 10.1.4.134
  edge:
    r0:
      ipv4_address: 10.1.5.129
    r1:
      ipv4_address: 10.1.5.130
    s0:
      ipv4_address: 10.1.5.131
    s1:
      ipv4_address: 10.1.5.132
    upfa1:
      ipv4_address: 10.1.5.133
    upfa2:
      ipv4_address: 10.1.5.134
  service:
    s:
      ipv4_address: 10.4.0.1
  slice0:
    subnet:
      ipv4_address: 10.2.0.0/24
  slice0-static:
    subnet:
      ipv4_address: 10.2.0.128/25
  slice1:
    subnet:
      ipv4_address: 10.2.1.0/24
  slice1-e1:
    subnet:
      ipv4_address: 10.2.1.0/26
  slice1-e1-static:
    subnet:
      ipv4_address: 10.2.1.64/26
  slice1-e2:
    subnet:
      ipv4_address: 10.2.1.128/26
  slice1-e2-static:
    subnet:
      ipv4_address: 10.2.1.192/26
  srgw0:
    subnet:
      ipv6_address: fc00:1::/32
    srgw0:
      ipv4_address: 10.3.0.1
    end-m-gtp4-e:
      ipv6_prefix: fc00:1:1::/48
    gnb1:
      ipv6_address: fc00:1:1:0A01:0481:0000:0000:0100 # fc00:1:1 + hex(gnb1) = hex(10.1.4.129) = 0A 01 04 81 + Args.Mob.Session ( 0 + 0000 0001) + padding
    gnb2:
      ipv6_address: fc00:1:1:0A01:0482:0000:0000:0100 # fc00:1:1 + hex(gnb2) = hex(10.1.4.130) = 0A 01 04 82 + Args.Mob.Session ( 0 + 0000 0001) + padding

  r0:
    subnet:
      ipv6_address: fc00:2::/32
    end-dx4:
      ipv6_address: "fc00:2:1::"
      ipv6_prefix: fc00:2:1::/48
  r1:
    subnet:
      ipv6_address: fc00:3::/32
    end-dx4:
      ipv6_address: "fc00:3:1::"
      ipv6_prefix: fc00:3:1::/48
  rr:
    subnet:
      ipv6_address: fc00:4::/32
    end:
      ipv6_prefix: fc00:4:1::/48
      ipv6_address: "fc00:4:1::"
